name: BLAKE3 JNI ABI Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-x64-glibc:
    name: Linux x64 glibc
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: common:jvmTest
        run: ./gradlew --no-daemon :common:jvmTest
      - name: BUILD sample2:build
        run: ./gradlew --no-daemon :sample2:build
      - name: BENCHMARK
        run: ./gradlew --no-daemon :benchmark:jvmBenchmark

  linux-x64-musl:
    name: Linux x64 musl
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk add --no-cache openjdk21 gradle bash
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
      - name: common:jvmTest
        run: /usr/bin/gradle --no-daemon :common:jvmTest
      - name: BUILD sample2:build
        run: /usr/bin/gradle --no-daemon :sample2:build
      - name: BENCHMARK
        run: /usr/bin/gradle --no-daemon :benchmark:jvmBenchmark
