name: BLAKE3 JNI ABI Test - Linux x64 musl

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-x64-musl:
    name: Linux x64 musl
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Install dependencies
        run: apk add --no-cache openjdk21 bash gcc g++ make nasm linux-headers
      - name: common:jvmTest
        run: ./gradlew --no-daemon :common:jvmTest
      - name: BENCHMARK
        run: ./gradlew --no-daemon :benchmark:jvmBenchmark
      # Note: Kotlin/KMPはmusl環境でのリンク/実行をサポートしないのでsample2をビルドできない
