name: build matrix - macOS x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-matrix-host.yml
    with:
      host: MacosX64
      runner: macos-15-intel
      test_tasks: linkDebugExecutableMacosArm64 linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64
      benchmark_tasks: linkReleaseExecutableMacosArm64 linkReleaseExecutableLinuxX64 linkReleaseExecutableLinuxArm64 linkReleaseExecutableMingwX64
      sample2_tasks: linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64 linkDebugExecutableMacosArm64
      sample2_targets: LinuxX64 LinuxArm64 MingwX64 MacosArm64
      empty_tasks: linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64 linkDebugExecutableMacosArm64
      empty_targets: LinuxX64 LinuxArm64 MingwX64 MacosArm64
