name: build matrix - macOS x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-matrix-host.yml
    with:
      host: MacosX64
      runner: macos-15-intel
      sample2_tasks: linkDebugExecutableMacosArm64
      sample2_targets: MacosArm64
