name: build matrix - Linux x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-matrix-host.yml
    with:
      host: LinuxX64
      runner: ubuntu-24.04
      test_tasks: linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64
      benchmark_tasks: linkReleaseExecutableLinuxX64 linkReleaseExecutableLinuxArm64 linkReleaseExecutableMingwX64
      sample2_tasks: linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64
      sample2_targets: LinuxX64 LinuxArm64 MingwX64
      empty_tasks: linkDebugExecutableLinuxX64 linkDebugExecutableLinuxArm64 linkDebugExecutableMingwX64
      empty_targets: LinuxX64 LinuxArm64 MingwX64
