name: common artifact - macOS arm64

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      host: MacosArm64
      runner: macos-15
