name: common artifact - all hosts

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  linux-x64:
    uses: ./.github/workflows/common-linux-x64.yml
    secrets: inherit

  mingw-x64:
    uses: ./.github/workflows/common-mingw-x64.yml
    secrets: inherit

  macos-arm64:
    uses: ./.github/workflows/common-macos-arm64.yml
    secrets: inherit

  collect:
    name: Collect common artifacts
    needs: [linux-x64, mingw-x64, macos-arm64]
    runs-on: ubuntu-24.04
    steps:
      - name: Download Linux x64 common artifact
        uses: actions/download-artifact@v4
        with:
          name: common-artifact-LinuxX64
          path: workflowResult/LinuxX64

      - name: Download macOS arm64 common artifact
        uses: actions/download-artifact@v4
        with:
          name: common-artifact-MacosArm64
          path: workflowResult/MacosArm64

      - name: Download Mingw X64 common artifact
        uses: actions/download-artifact@v4
        with:
          name: common-artifact-MingwX64
          path: workflowResult/MingwX64

      - name: Upload collected common artifacts
        uses: actions/upload-artifact@v4
        with:
          name: common-artifacts
          path: workflowResult
          if-no-files-found: error
