name: common-jvm jar - all hosts

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  linux-x64:
    uses: ./.github/workflows/common-jvm-jar-linux-x64.yml

  macos-x64:
    uses: ./.github/workflows/common-jvm-jar-macos-x64.yml

  macos-arm64:
    uses: ./.github/workflows/common-jvm-jar-macos-arm64.yml

  windows-x64:
    uses: ./.github/workflows/common-jvm-jar-mingw-x64.yml

  collect:
    name: Collect common.jar files
    needs: [linux-x64, macos-x64, macos-arm64, windows-x64]
    runs-on: ubuntu-24.04
    steps:
      - name: Download Linux x64 common.jar
        uses: actions/download-artifact@v4
        with:
          name: common-jar-LinuxX64
          path: workflowResult/LinuxX64

      - name: Download macOS x64 common.jar
        uses: actions/download-artifact@v4
        with:
          name: common-jar-MacosX64
          path: workflowResult/MacosX64

      - name: Download macOS arm64 common.jar
        uses: actions/download-artifact@v4
        with:
          name: common-jar-MacosArm64
          path: workflowResult/MacosArm64

      - name: Download Mingw X64 common.jar
        uses: actions/download-artifact@v4
        with:
          name: common-jar-MingwX64
          path: workflowResult/MingwX64

      - name: Upload collected common.jar files
        uses: actions/upload-artifact@v4
        with:
          name: common-jars
          path: workflowResult
          if-no-files-found: error
