name: common-jvm jar - Linux x64

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/common-jvm-jar-host.yml
    with:
      host: LinuxX64
      runner: ubuntu-24.04
      expected_targets: "LinuxX64 LinuxArm64 WindowsX64 WindowsArm64"
      expected_resources: "linux-x86_64 linux-aarch64 windows-x86_64 windows-aarch64"
      extra_gradle_args: "-PLinuxX64_WindowsArm64_compiler=aarch64-w64-mingw32-clang -PLinuxX64_WindowsArm64_linkOpt=-shared"
