name: common-jvm jar - Windows x64

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/common-jvm-jar-host.yml
    with:
      host: WindowsX64
      runner: windows-2025
      expected_targets: "WindowsX64"
      expected_resources: "windows-x86_64 windows-aarch64"
      extra_gradle_args: "-PWindowsX64_WindowsArm64_compiler=aarch64-w64-mingw32-clang -PWindowsX64_WindowsArm64_linkOpt=-shared"
