name: build matrix - Linux x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: LinuxX64
      runner: ubuntu-24.04
