name: build matrix - all hosts

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-x64:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: LinuxX64
      runner: ubuntu-24.04

  windows-x64:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: MingwX64
      runner: windows-2025

  macos-arm64:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: MacosArm64
      runner: macos-15

  macos-x64:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: MacosX64
      runner: macos-15-intel
