name: build matrix - Windows x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/nativeBinaries.yml
    with:
      host: MingwX64
      runner: windows-2025
