name: sample2 - Linux x64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sample2-linux-x64:
    name: Linux x64
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"
      - name: Run sample2
        run: ./runSample2.sh
